import type { Hub } from '../src/server.js';
import { patchMilestone } from '../src/projects/roadmap.js';
import { POMODORO_DOCS, POMODORO_PRD, POMODORO_WORKSPACE } from './content.js';

/** An authenticated call to the running hub; resolves with the parsed body, throws on a non-2xx. */
export type HubCall = (method: string, path: string, body?: unknown) => Promise<any>;

/** A plan route answers 200 and then streams; its outcome is the last `data:` frame. */
async function planned(call: HubCall, path: string, body: unknown = {}): Promise<void> {
  const stream = String(await call('POST', path, body));
  const frames = [...stream.matchAll(/^data: (.*)$/gm)].map((m) => JSON.parse(m[1]!) as { done?: boolean; error?: string });
  const last = frames[frames.length - 1];
  if (!last?.done) throw new Error(`${path} did not finish: ${last?.error ?? stream.slice(0, 200)}`);
}

/**
 * Puts the three simulation projects in, through the hub's own routes wherever one exists — the
 * same calls the UI makes — and through the bundle only for what no route writes (docs pages, and
 * the first milestone's verified history). Each project shows a different stage of life:
 *
 * - `pomodoro-cli`: full PRD, 9 milestones with m1–m3 done and verified (m2 and m3 by real turns
 *   against the scripted model), docs, a code map, workspace files and a preview.
 * - `habit-tracker`: PRD drafted and roadmap generated by the model, nothing built.
 * - `scratch`: just created; the PRD is the scaffold.
 *
 * Returns one line per project for the startup banner.
 */
export async function seedProjects(call: HubCall, hub: Hub, opts: { previewAppPort: number }): Promise<string[]> {
  // pomodoro-cli ------------------------------------------------------------------------------
  const pomodoro = 'pomodoro-cli';
  await call('POST', '/api/projects', {
    slug: pomodoro, title: 'Pomodoro CLI',
    intent: 'A terminal Pomodoro timer that logs every session and shows daily focus stats.',
  });
  await call('PUT', `/api/projects/${pomodoro}/prd`, { markdown: POMODORO_PRD });
  await planned(call, `/api/projects/${pomodoro}/roadmap/generate`);
  for (const [path, text] of Object.entries(POMODORO_WORKSPACE)) {
    await call('PUT', `/api/projects/${pomodoro}/code/file`, { path, text });
  }
  await call('PUT', `/api/projects/${pomodoro}/preview`, { cmd: ['node', 'serve.mjs'], port: opts.previewAppPort });

  // No route writes docs pages or a milestone's verification (only complete_milestone does, inside
  // a turn), so the history before the first simulated turn goes in through the bundle.
  const bundle = await hub.projects.get(pomodoro);
  for (const [slug, markdown] of Object.entries(POMODORO_DOCS)) await bundle.writeDoc(slug, markdown);
  const at = Date.now() - 2 * 60 * 60_000;
  await bundle.writeRoadmap(patchMilestone(await bundle.roadmap(), 'm1', {
    status: 'done',
    verification: { tests: 'pass', review: 'approved', at, notes: 'tests: pass (npm test, exit 0); review: approved (Vex)' },
  }));
  await bundle.appendDecision({
    title: 'Milestone m1 verified and done',
    rationale: 'CLI skeleton and timer core — tests: pass (npm test, exit 0); review: approved (Vex). The timer reads the wall clock rather than counting ticks, so it cannot drift.',
    by: 'agent',
  });
  await bundle.commit('sim: m1 history and docs');

  // Two real turns against the scripted model: each one delegates, verifies and briefs a milestone.
  await call('POST', `/api/projects/${pomodoro}/turn`, {});
  await call('POST', `/api/projects/${pomodoro}/turn`, {});
  await call('POST', `/api/projects/${pomodoro}/code/map`, {});

  // habit-tracker -----------------------------------------------------------------------------
  const habit = 'habit-tracker';
  await call('POST', '/api/projects', {
    slug: habit, title: 'Habit Tracker',
    intent: 'A private, offline-first habit tracker with streaks.',
    idea: 'Track a handful of daily habits, tick them off in seconds, and see streaks and a month heat map. Just for me, works offline on my phone.',
  });
  await planned(call, `/api/projects/${habit}/prd/draft`);
  await planned(call, `/api/projects/${habit}/roadmap/generate`);

  // scratch -----------------------------------------------------------------------------------
  await call('POST', '/api/projects', {
    slug: 'scratch', title: 'Scratch', intent: 'A place to try ideas before they become projects.',
  });

  return [
    `${pomodoro}   PRD, 9 milestones (m1–m3 done + verified), 2 turns, docs, code map, workspace, preview`,
    `${habit}  PRD drafted, roadmap generated, nothing built`,
    `scratch        just created (scaffold PRD)`,
  ];
}
